# Generated by Django 5.0.2 on 2024-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('last_active', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
